services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  node-app:
    build: .
    container_name: feria-node
    restart: always
    depends_on:
      - postgres-db
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data  # si tu CSV está en /data
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  pgdata:
